apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
<<<<<<< HEAD
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
=======
    repoURL: https://github.com/RichardKiely/-argocd-app-config.git
>>>>>>> 0b987926c1fda1ff4abeb27cb20ff4b02eb9829d
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
<<<<<<< HEAD
      prune: true
=======
      prune: true
>>>>>>> 0b987926c1fda1ff4abeb27cb20ff4b02eb9829d
